### ISSUE TITLE
.css files must have a Front Matter block

### ISSUE THREAD

**Issue by vincecima** [mhanberg/jekyll-postcss#1]
Thanks again for building this converter. I think it might be useful to add a note stating that the `*.css` files are only passed to the plugin if they have a Front Matter block. The documentation on the main Jekyll site sort of buries this.

**Comment by pixelastic** [comment]
Agreed, took me a while to understand why nothing was happening.

**Comment by mhanberg** [comment]
Happy to accept a PR with this added to the "Note" section in the README

**Comment by pixelastic** [comment]
Submitted #3 for that. Hope that's clear enough

**Comment by mhanberg** [comment]
Closed by #3
