### ISSUE TITLE
Clearly document JEKYLL_ENV requirement on build environments

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/jekyll-postcss#14]
> I think this needs to be  more stressed. I figured the reason you mentioned it is that you're using the env variable in the postcss config on your demo repo only. I didn't realize it would hang in netlify and y local docker env.

_Originally posted by @steveoh in https://github.com/mhanberg/jekyll-postcss/issues/8#issuecomment-632426397_

## Acceptance Criteria

- [x] The readme should clearly state that you should definitely set the `JEKYLL_ENV` in your build environment, or else your build is liable to hang and then fail.

**Comment by steveoh** [comment]
This bit me in docker as well as netlify. 

currently debugging this issue now...

```
/usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '⚠️  Tailwind is not purging unused styles because no template paths have been provided. (JSON::ParserError)
If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
removing unused styles, set `purge: false` in your Tailwind config file to silence
this warning.
```

**Comment by mhanberg** [comment]
Can you elaborate on what JEKYLL_ENV has to do with that error? To me it looks like a tailwind misconfiguration.

**Comment by steveoh** [comment]
> Can you elaborate on what JEKYLL_ENV has to do with that error? To me it looks like a tailwind misconfiguration.

Sorry yah they arent related. I should open a new issue if I wanted some help with that. I'll see if I can get it working first. 

I should elaborate that my dev build env is docker so the jekyll build fails for me in development.
