### ISSUE TITLE
Development cache does not work when you build multiple css files

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/jekyll-postcss#18]
If you are building multiple css files, development caching does not work.

Your css will still be successfully processed, but it will take up to 3 seconds every build, even if you are only editing markdown files.

**Comment by mhanberg** [comment]
The converter uses the same object instance for every document, and the the converter is not passed the filename, only the content to convert. 

I don't know if if this will be fixable. I might have to clarify that you can only have one stylesheet if you want caching to work 😐.

**Comment by bvirlet** [comment]
I'm having the same problem (20s builds instead of 1s) with multiple stylesheets. While I understand why there isn't a solution for this, is there a potential workaround?

**Comment by mhanberg** [comment]
I believe the work around is to not build multiple css files.

**Comment by mhanberg** [comment]
There is now a feature to disable the cache, this should solve this i think.
