### ISSUE TITLE
Documentation: Can Jekyll Server be used?

### ISSUE THREAD

**Issue by rebelwarrior** [mhanberg/jekyll-postcss#26]
Can Jekyll server be used with jekyll-postcss?
I can't find any documentation on that and it's not working for me.

**Comment by mhanberg** [comment]
You should be able to use Jekyll as you normally would `bundle exec jekyll serve`. 

What problem are you having?

**Comment by rebelwarrior** [comment]
I get this
`bundle exec jekyll serve --config _config.dev.yml`
```
Configuration file: /Users/david/Code/Elm/demo-tailwind-elm-doc-builder/_config.dev.yml
PostCSS Server listening on port 8124...
```

**Comment by rebelwarrior** [comment]
and then it hangs.... does nothing.

**Comment by mhanberg** [comment]
I think I've been seeing this lately as well. 

Not sure what the cause is but restarting it a couple times usually works for me. 

Could you share your ruby, node, jekyll, and postcss versions?

**Comment by rebelwarrior** [comment]
ruby version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
node version: v14.16.1
jekyll version: jekyll (4.2.0)
postcss.... 8.2.13
```
demo-tailwind-elm-doc-builder [main] % npm list postcss
/Users/davidacevedo
└─┬ tailwindcss@2.1.2
  ├─┬ @fullhuman/postcss-purgecss@3.1.3
  │ └─┬ purgecss@3.1.3
  │   └── postcss@8.2.13  deduped
  ├─┬ postcss-functions@3.0.0
  │ └── postcss@6.0.23  extraneous
  └─┬ postcss-js@3.0.3
    └── postcss@8.2.13
```

**Comment by rebelwarrior** [comment]
Would this plugin need a call out in the default layout to work?

**Comment by mhanberg** [comment]
No.

**Comment by rebelwarrior** [comment]
~~Found the problem. ~~ (Nope: I didn't) 

~~if you use a main.scss file it will fail. You have to use a main.css file. This can be clearer in the documentation. Also not sure why this causes the problem. 
_sass/main.css~~
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

**Comment by rebelwarrior** [comment]
Nope nevermind. it's not working again.

**Comment by rebelwarrior** [comment]
If I keep trying it work sometimes. So it's not a consistent problem one thing I can say is that when it works the postcss server launches after the jekyll one gets going. 
```
demo-tailwind-elm-doc-builder [main●●] % jekyll-dev --trace
Configuration file: /Users/davidacevedo/Code/Elm/demo-tailwind-elm-doc-builder/_config.dev.yml
            Source: /Users/davidacevedo/Code/Elm/demo-tailwind-elm-doc-builder
       Destination: /Users/davidacevedo/Code/Elm/demo-tailwind-elm-doc-builder/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
PostCSS Server listening on port 8124...
       Jekyll Feed: Generating feed for posts

```

**Comment by rebelwarrior** [comment]
Suspecting this is a thread issue. It runs fine every time with JRuby.

**Comment by rebelwarrior** [comment]
runs well under ruby 2.7.3 as well.

**Comment by Atem18** [comment]
@rebelwarrior How big is your website ?

**Comment by rebelwarrior** [comment]
It’s empty at the moment.

**Comment by Atem18** [comment]
Then maybe do a strace to see where the process hangs. And you speak about JRuby, which platform are you using ?

**Comment by rebelwarrior** [comment]
I’m on a Mac. But it’s not JRuby that fixes it, it’s the older ruby version. It works under 2.7 MRI as well.

**Comment by Atem18** [comment]
Ruby 3 is still new, I am not sure how far it is supported.

**Comment by mhanberg** [comment]
@rebelwarrior I think i fixed this. try updating to 0.4.1 and let me know if you are still having problems
