### ISSUE TITLE
Can't include files

### ISSUE THREAD

**Issue by typhoon2099** [mhanberg/jekyll-postcss#5]
I have a file in my Jekyll build called `css/index.css`, and I would like to import a file called `_includes/variables.css`. I have added the following to `index.css`:

```
---
---

@import "_includes/variables"
```

However, I'm getting the following error while trying to build my site:
```
Error: Failed to find '_includes/variables'
  in [
    /path/to/project
  ]
    at resolveModule.catch.catch (/path/to/project/node_modules/postcss-import/lib/resolve-id.js:35:13)
  Conversion error: Jekyll::Converters::PostCss encountered an error while converting 'css/index.css':
                    PostCssRuntimeError
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

I have used your blog as an example of setup, postcss-import is included, but I can't figure out why my `variables` file isn't being imported. I've tried moving it around my repo, and changing the `@import` with no success. I could work around this by using `{% include variables.css %}`, but I don't want to do that (I'd rather use as much CSS as possible).

What's the correct procedure for inlining imports when using `jekyll-postcss`?

**Comment by typhoon2099** [comment]
Figured it out, the imports are relative to the repo root, not the Jekyll root. I keep everything in a `jekyll` directory so I don't have to exclude build files etc.

**Comment by mhanberg** [comment]
Glad you figured it out!
